### ISSUE TITLE
No active connection

### ISSUE THREAD

**Issue by joiner3710** [jum4/sublime-sqlexec#14]
i followed the steps but if i use ctrl+e 2x tell me "No active connection"

**Comment by JamesCrittenden** [comment]
Has anyone figured out a solution for this? The no active connection error still pops up

**Comment by bendilley** [comment]
I've installed sqlexec using package manager on sublime build 3083 and I'm sure I've set up and selected my pgsql connection correctly (from the list of two valid connections), along with a working `~/.pgpass` (I can connect via `psql` in cmd), yet I still get "No active connection" pop up for every attempt to execute.

I've also tried setting `"sql_exec.debug": true`, but that doesn't seem to be any more verbose, and an absolute path to `psql`, but that hasn't worked either. Below is my current `SQLExec.sublime-settings` with a couple of name changes (the latter connection is an ssh tunnel):

``` json
{
  "sql_exec.debug": true,
  "sql_exec.commands": {
    "pgsql": "/usr/local/bin/psql"
  },
  "connections": {
    "ssnext@dev": {
      "type": "pgsql",
      "host": "localhost",
      "port": 5432,
      "username": "foo",
      "database": "bar"
    },
    "ssnext@qa": {
      "type": "pgsql",
      "host": "localhost",
      "port": 5433,
      "username": "foo",
      "database": "bar2"
    }
  }
}
```

Can you see something I can't?

**Comment by Skoffer** [comment]
I have the same issue. My file looks like this: 

``` json
{
    "sql_exec.debug": true,
    "sql_exec.commands": {
        "mysql"  : "mysql",
        "pgsql"  : "psql",
        "oracle" : "sqlplus",
        "vertica": "vsql"
    },
    "connections": {
        "Conn1":   {
                         "type"    : "pgsql",
                         "host"    : "127.0.0.1",
                         "port"    :  5432,
                         "username": "postgres",
                         "database": "postgres"
                        }
    }
}
```

**Comment by nicobrenner** [comment]
The connection worked fine from the command line:

`psql -U nico development_database`

Was getting the same error message without any additional details.

The problem is that despite not needing a password for the connection, the configuration file needs to have a `password` field, otherwise the plugin throws an error in the console when selecting the connection.

Changed my config file to this:
```
{
  "connections": {
    "Dev DB": {
      "type"    : "pgsql",
      "host"    : "127.0.0.1",
      "port"    : 5432,
      "username": "nico",
      "password": "",
      "database": "development_database"
    }
  }
}
```

But then got this error:

`/bin/sh: psql: command not found`

Which is solved here: https://github.com/jum4/sublime-sqlexec/issues/17

Config file now looks like this:

```
{
  "sql_exec.commands": {
    "pgsql" : "/usr/local/bin/psql"
  },

  "connections": {
    "Dev DB": {
      "type"    : "pgsql",
      "host"    : "127.0.0.1",
      "port"    : 5432,
      "username": "nico",
      "password": "",
      "database": "development_database"
    }
  }
}
```

Note: installed Postgres using Homebrew

**Comment by bendilley** [comment]
Adding `"password": ""` to the connection properties worked for me too. Thanks @nicobrenner!
