### ISSUE TITLE
PGSQL postgres connector disconsiders password (workaround found)

### ISSUE THREAD

**Issue by fgielow** [jum4/sublime-sqlexec#53]
Hi there,

currently a connection like this discosiders the password:

``` json
{
    "connections": {
        "dev": {
            "type"    : "pgsql",
            "host"    : "localhost",
            "port"    : 5432,
            "username": "username",
            "password": "passssssword",
            "database": "dev"
        }
    }
}
```

pgsql.sqlexec does not apply options.password anywhere (because the psql command does not support it, I am aware). 

However, you can give the password as a PGPASSWORD parameter in bash. Hence, here is my current workaround for if anybody needs it:

``` json
{
    "sql_exec.commands": {
        "pgsql"  : "PGPASSWORD=passssssword /usr/local/bin/psql",
    },
    "connections": {
        "dev": {
            "type"    : "pgsql",
            "host"    : "localhost",
            "port"    : 5432,
            "username": "username",
            "password": "",
            "database": "dev"
        }
    }
}
```

**Comment by jum4** [comment]
Hi,
In the documentation, I recommended to use PostgreSQL pgpass.conf file for storing postgresql passwords. This is the solution recommended by PostgreSQL documentation. 
I think SQLExec should not required the password for postgreSQL connections.

Your workaround seems not to work on windows, I think the pgpass.conf is a better way, and it is very simple to implement: http://www.postgresql.org/docs/9.1/static/libpq-pgpass.html

**Comment by evandrocoan** [comment]
Well, I am on windows and this `pgpass.conf` is not working. But I am able to run a shell script as this by my build file. I am on Windows 10 with Cygwin programs on the path:

SQL.sh

```
PGPASSWORD=admin;
psql --host "localhost" --port 5432 --username "postgres" -d "aula23" < $1
```

SQL.sublime-build

```
{
    "working_dir": "$file_path",
    "selector": "source.sql",

    "cmd": ["sh","$packages/SQL/sql.sh","$file", "$file_name"],
    "target": "ansi_color_build",
}
```

May this package implement it, so password field on the settings file became useful?
